[workspace]
members = ["crates/kouga-core", "crates/kouga-runtime", "crates/kouga-validation", "crates/kouga-db", "crates/kouga-request-derive", "crates/kouga-migration", "crates/kouga-http", "crates/kouga-http-derive", "crates/kouga-model", "crates/kouga-job", "crates/kouga-job-derive", "crates/kouga-queue", "crates/kouga-telemetry", "crates/kouga-mailer"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.94"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
kouga-core = { path = "crates/kouga-core" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
