[package]
name = "kouga-migration"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kouga-db = { path = "../kouga-db" }
sqlx = { version = "=0.9.0", default-features = false, features = ["postgres", "runtime-tokio", "tls-rustls-ring-native-roots"] }
sha2 = "=0.10.9"
chrono = "=0.4.45"
tokio = { version = "=1.53.1", features = ["time"] }

[dev-dependencies]
tokio = { version = "=1.53.1", features = ["macros", "rt-multi-thread", "time"] }
