[package]
name = "kouga-openapi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kouga-http = { path = "../kouga-http" }
serde_json.workspace = true
axum = { version = "=0.8.9", default-features = false, features = ["json"] }
utoipa-swagger-ui = { version = "=10.0.1", default-features = false, features = ["axum", "vendored"] }
utoipa = { version = "=6.0.0", default-features = false }
jsonschema = { version = "=0.57.0", default-features = false }

[dev-dependencies]
tower = { version = "=0.5.3", features = ["util"] }
tokio = { version = "=1.53.1", features = ["macros", "rt"] }
kouga-validation = { path = "../kouga-validation" }
serde.workspace = true
